import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { categories, questions, options, votes, impressions } from "./schema";

// Ensure DATABASE_URL is set before running:
//   DATABASE_URL=postgres://user:pass@localhost:5432/dbname tsx src/lib/db/seed.ts
// Or use the npm script with .env.local loaded:
//   source .env.local && npm run db:seed

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const db = drizzle(pool);

// ---------------------------------------------------------------------------
// Seed data
// ---------------------------------------------------------------------------

const categoryData = [
  {
    name: "Music",
    slug: "music",
    description: "Debates about songs, artists, albums, and performances",
    iconEmoji: "🎵",
  },
  {
    name: "Food",
    slug: "food",
    description: "The eternal arguments about what tastes best",
    iconEmoji: "🍕",
  },
  {
    name: "Movies",
    slug: "movies",
    description: "Silver screen showdowns and casting debates",
    iconEmoji: "🎬",
  },
  {
    name: "TV",
    slug: "tv",
    description: "The golden age of television, ranked",
    iconEmoji: "📺",
  },
  {
    name: "Sports",
    slug: "sports",
    description: "GOAT debates and legendary matchups",
    iconEmoji: "🏆",
  },
  {
    name: "Culture",
    slug: "culture",
    description: "Pop culture, social media, and the way we live now",
    iconEmoji: "🌍",
  },
  {
    name: "Gaming",
    slug: "gaming",
    description: "Console wars, game rankings, and player legends",
    iconEmoji: "🎮",
  },
  {
    name: "Style",
    slug: "style",
    description: "Fashion, sneakers, and aesthetic choices",
    iconEmoji: "👟",
  },
];

// Questions organized by category slug.
// Each entry: { prompt, subtitle?, tags?, options: string[] }
const questionData: Record<
  string,
  {
    prompt: string;
    subtitle?: string;
    tags?: string[];
    options: string[];
  }[]
> = {
  music: [
    { prompt: "Who did the best cover of Hallelujah?", subtitle: "Leonard Cohen's masterpiece has been covered countless times", tags: ["music", "covers"], options: ["Jeff Buckley", "Leonard Cohen", "Rufus Wainwright", "Pentatonix"] },
    { prompt: "What's the greatest guitar solo of all time?", tags: ["music", "guitar"], options: ["Stairway to Heaven", "Comfortably Numb", "Free Bird", "Hotel California"] },
    { prompt: "Who's the greatest rapper of all time?", tags: ["music", "hip-hop"], options: ["Tupac", "Biggie", "Jay-Z", "Eminem"] },
    { prompt: "What's the best album of the 2010s?", tags: ["music", "albums"], options: ["My Beautiful Dark Twisted Fantasy", "To Pimp a Butterfly", "1989", "Blonde"] },
    { prompt: "Who has the best catalog for a Verzuz battle?", subtitle: "Depth, hits, and cultural impact all matter", tags: ["music", "hip-hop"], options: ["Missy Elliott", "Timbaland", "The Neptunes", "Swizz Beatz"] },
    { prompt: "Who's the best live performer?", tags: ["music", "performance"], options: ["Beyonce", "Bruce Springsteen", "Freddie Mercury", "Prince"] },
    { prompt: "What's the best movie soundtrack?", tags: ["music", "movies"], options: ["Purple Rain", "The Bodyguard", "Saturday Night Fever", "Black Panther"] },
    { prompt: "What's the greatest debut album ever?", tags: ["music", "albums"], options: ["Appetite for Destruction", "The Chronic", "Illmatic", "Is This It"] },
    { prompt: "Who's the best female vocalist of all time?", subtitle: "Pure vocal ability and range", tags: ["music", "vocals"], options: ["Whitney Houston", "Mariah Carey", "Aretha Franklin", "Celine Dion"] },
    { prompt: "What's the best Beatles album?", tags: ["music", "albums", "classic-rock"], options: ["Abbey Road", "Sgt. Pepper's", "Revolver", "The White Album"] },
    { prompt: "Who had the best breakup album?", tags: ["music", "albums"], options: ["Adele - 21", "Fleetwood Mac - Rumours", "Taylor Swift - Red", "Marvin Gaye - Here, My Dear"] },
    { prompt: "What's the greatest bassline ever?", tags: ["music", "bass"], options: ["Come Together", "Another One Bites the Dust", "Billie Jean", "Superstition"] },
    { prompt: "Who's the best drummer of all time?", subtitle: "Technical skill meets musicality", tags: ["music", "drums"], options: ["John Bonham", "Neil Peart", "Keith Moon", "Buddy Rich"] },
    { prompt: "What's the most iconic music video?", tags: ["music", "music-videos"], options: ["Thriller", "Take On Me", "Sledgehammer", "Vogue"] },
    { prompt: "Who made the best Christmas album?", tags: ["music", "albums", "holidays"], options: ["Mariah Carey", "Nat King Cole", "Michael Buble", "Pentatonix"] },
    { prompt: "What's the best 90s hip-hop album?", tags: ["music", "hip-hop", "albums"], options: ["The Chronic", "Ready to Die", "Illmatic", "The Miseducation of Lauryn Hill"] },
    { prompt: "Who's the best one-hit wonder?", subtitle: "That one perfect song", tags: ["music", "pop"], options: ["Soft Cell - Tainted Love", "A-ha - Take On Me", "Dexys Midnight Runners - Come On Eileen", "Los Del Rio - Macarena"] },
    { prompt: "What's the greatest love song?", tags: ["music", "romance"], options: ["At Last", "Unchained Melody", "I Will Always Love You", "Wonderful Tonight"] },
    { prompt: "Who's the best protest song artist?", tags: ["music", "protest"], options: ["Bob Dylan", "Public Enemy", "Rage Against the Machine", "Nina Simone"] },
    { prompt: "What's the best collaboration of all time?", subtitle: "When two legends unite", tags: ["music", "collabs"], options: ["Empire State of Mind", "Walk This Way", "Endless Love", "Under Pressure"] },
    { prompt: "Who's the greatest music producer?", tags: ["music", "production"], options: ["Quincy Jones", "Rick Rubin", "Dr. Dre", "Pharrell Williams"] },
    { prompt: "What's the best 80s pop album?", tags: ["music", "albums", "pop"], options: ["Thriller", "Purple Rain", "Like a Virgin", "Faith"] },
    { prompt: "Who's the best country singer?", tags: ["music", "country"], options: ["Johnny Cash", "Dolly Parton", "Garth Brooks", "Willie Nelson"] },
    { prompt: "What's the greatest rock anthem?", tags: ["music", "rock"], options: ["Bohemian Rhapsody", "Don't Stop Believin'", "We Will Rock You", "Sweet Child O' Mine"] },
    { prompt: "Who had the best MTV Unplugged performance?", subtitle: "Stripped down, raw talent", tags: ["music", "performance"], options: ["Nirvana", "Eric Clapton", "Lauryn Hill", "Alice in Chains"] },
    { prompt: "What's the best concept album?", tags: ["music", "albums"], options: ["The Wall", "American Idiot", "good kid, m.A.A.d city", "Tommy"] },
    { prompt: "Who's the best boy band?", tags: ["music", "pop", "boy-bands"], options: ["Backstreet Boys", "NSYNC", "One Direction", "BTS"] },
    { prompt: "What's the best girl group?", tags: ["music", "pop", "girl-groups"], options: ["Destiny's Child", "The Supremes", "TLC", "Spice Girls"] },
    { prompt: "Who's the greatest jazz musician?", tags: ["music", "jazz"], options: ["Miles Davis", "John Coltrane", "Louis Armstrong", "Charlie Parker"] },
    { prompt: "What's the best live album?", subtitle: "Capturing lightning in a bottle", tags: ["music", "albums", "performance"], options: ["Live at Folsom Prison", "Unplugged in New York", "At Fillmore East", "Stop Making Sense"] },
    { prompt: "Who's the best electronic/DJ artist?", tags: ["music", "electronic", "djs"], options: ["Daft Punk", "The Chemical Brothers", "Deadmau5", "Calvin Harris"] },
    { prompt: "What's the greatest punk album?", tags: ["music", "punk", "albums"], options: ["London Calling", "Never Mind the Bollocks", "Dookie", "Ramones"] },
    { prompt: "Who wrote the best songs?", tags: ["music", "songwriting"], options: ["Bob Dylan", "Paul McCartney", "Carole King", "Stevie Wonder"] },
    { prompt: "What's the best music era?", tags: ["music", "eras"], options: ["60s Rock Revolution", "70s Disco & Funk", "80s Pop Explosion", "90s Hip-Hop Golden Age"] },
    { prompt: "Who's the best metal band?", tags: ["music", "metal"], options: ["Metallica", "Black Sabbath", "Iron Maiden", "Slayer"] },
    { prompt: "What's the best opening track on an album?", subtitle: "Setting the tone perfectly", tags: ["music", "albums"], options: ["Smells Like Teen Spirit", "Welcome to the Jungle", "Good Morning", "Dark Fantasy"] },
    { prompt: "Who has the best vocal range?", tags: ["music", "vocals"], options: ["Freddie Mercury", "Mariah Carey", "Axl Rose", "Mike Patton"] },
    { prompt: "What's the greatest classical composition?", tags: ["music", "classical"], options: ["Beethoven's 9th Symphony", "Mozart's Requiem", "Vivaldi's Four Seasons", "Bach's Brandenburg Concertos"] },
    { prompt: "Who's the best indie rock band?", tags: ["music", "indie", "rock"], options: ["Radiohead", "Arcade Fire", "The Strokes", "Arctic Monkeys"] },
    { prompt: "What's the best album closer?", tags: ["music", "albums"], options: ["A Day in the Life", "Jungleland", "Last Call", "All Too Well (10 Minute Version)"] },
    { prompt: "Who's the best R&B artist?", subtitle: "Smooth vocals and soulful vibes", tags: ["music", "rnb"], options: ["Stevie Wonder", "Marvin Gaye", "Usher", "Alicia Keys"] },
    { prompt: "What's the greatest music festival performance?", tags: ["music", "performance", "festivals"], options: ["Beyonce at Coachella 2018", "Jimi Hendrix at Woodstock", "Queen at Live Aid", "Daft Punk at Coachella 2006"] },
    { prompt: "Who's the best solo artist who left their band?", tags: ["music", "solo"], options: ["Paul McCartney", "Beyonce", "Phil Collins", "Robbie Williams"] },
    { prompt: "What's the best summer song?", tags: ["music", "pop"], options: ["California Girls", "Summertime", "Hot Fun in the Summertime", "Cruel Summer"] },
    { prompt: "Who's the most influential producer in hip-hop?", tags: ["music", "hip-hop", "production"], options: ["Dr. Dre", "J Dilla", "DJ Premier", "Kanye West"] },
    { prompt: "What's the best rock subgenre?", tags: ["music", "rock", "genres"], options: ["Classic Rock", "Punk Rock", "Grunge", "Progressive Rock"] },
    { prompt: "Who had the best comeback album?", subtitle: "Proving the doubters wrong", tags: ["music", "albums"], options: ["Johnny Cash - American Recordings", "Santana - Supernatural", "Tina Turner - Private Dancer", "John Lennon - Double Fantasy"] },
    { prompt: "What's the greatest drum solo?", tags: ["music", "drums"], options: ["Moby Dick", "In the Air Tonight", "Tom Sawyer", "Sing Sing Sing"] },
    { prompt: "Who's the best frontman/frontwoman?", tags: ["music", "performance"], options: ["Freddie Mercury", "Mick Jagger", "Janis Joplin", "James Brown"] },
    { prompt: "What's the best song to play at max volume?", tags: ["music", "rock"], options: ["Thunderstruck", "Killing in the Name", "Enter Sandman", "Rock and Roll"] },
    { prompt: "Who's the best singer-songwriter?", subtitle: "Writing and performing their own stories", tags: ["music", "songwriting"], options: ["Joni Mitchell", "Bob Dylan", "Leonard Cohen", "Taylor Swift"] },
    { prompt: "What's the best music documentary?", tags: ["music", "movies"], options: ["What's Going On", "Amy", "Searching for Sugar Man", "20 Feet from Stardom"] },
    { prompt: "Who's the best Latin music artist?", tags: ["music", "latin"], options: ["Shakira", "Bad Bunny", "Selena", "Daddy Yankee"] },
    { prompt: "What's the best karaoke song?", tags: ["music", "pop"], options: ["Don't Stop Believin'", "Livin' on a Prayer", "I Wanna Dance with Somebody", "Mr. Brightside"] },
    { prompt: "Who has the best discography with no skips?", subtitle: "Consistency across their entire career", tags: ["music", "albums"], options: ["Kendrick Lamar", "Kanye West", "Radiohead", "Outkast"] },
    { prompt: "What's the greatest concert venue?", tags: ["music", "venues"], options: ["Red Rocks Amphitheatre", "Madison Square Garden", "Royal Albert Hall", "The Fillmore"] },
    { prompt: "Who's the best acoustic guitarist?", tags: ["music", "guitar"], options: ["Tommy Emmanuel", "John Mayer", "Ed Sheeran", "Jose Gonzalez"] },
    { prompt: "What's the best album of the 2000s?", tags: ["music", "albums"], options: ["The Marshall Mathers LP", "Kid A", "Stankonia", "The Blueprint"] },
    { prompt: "Who had the best halftime show?", tags: ["music", "performance"], options: ["Prince", "Beyonce", "Michael Jackson", "Dr. Dre & Snoop Dogg"] },
    { prompt: "What's the greatest power ballad?", tags: ["music", "rock"], options: ["November Rain", "I Don't Want to Miss a Thing", "Every Rose Has Its Thorn", "Faithfully"] },
    { prompt: "Who's the best music icon of the 21st century?", subtitle: "Cultural impact, music, and influence", tags: ["music", "pop"], options: ["Beyonce", "Kanye West", "Taylor Swift", "Drake"] },
    { prompt: "What's the best workout song?", tags: ["music", "pop"], options: ["Eye of the Tiger", "Lose Yourself", "Stronger", "Till I Collapse"] },
  ],
  food: [
    { prompt: "Which city has the best pizza?", subtitle: "The eternal debate", tags: ["food", "pizza"], options: ["New York", "Chicago", "New Haven", "Detroit"] },
    { prompt: "What's the best breakfast food?", tags: ["food", "breakfast"], options: ["Pancakes", "Waffles", "French Toast", "Eggs Benedict"] },
    { prompt: "Who makes the best fast food burger?", tags: ["food", "fast-food"], options: ["In-N-Out", "Shake Shack", "Five Guys", "Whataburger"] },
    { prompt: "What's the best cuisine?", subtitle: "If you could only eat one forever", tags: ["food", "cuisine"], options: ["Italian", "Japanese", "Mexican", "Thai"] },
    { prompt: "Best late-night drunk food?", tags: ["food", "late-night"], options: ["Pizza", "Tacos", "Diner breakfast", "Kebab"] },
    { prompt: "What's the superior condiment?", tags: ["food", "condiments"], options: ["Ketchup", "Mayo", "Mustard", "Hot sauce"] },
    { prompt: "Best chip flavor?", subtitle: "The snack tier list", tags: ["food", "snacks"], options: ["Salt & Vinegar", "BBQ", "Sour Cream & Onion", "Cheddar"] },
    { prompt: "What's the best coffee order?", tags: ["food", "coffee"], options: ["Black coffee", "Latte", "Cappuccino", "Cold brew"] },
    { prompt: "Best taco filling?", tags: ["food", "mexican"], options: ["Carne asada", "Al pastor", "Carnitas", "Fish"] },
    { prompt: "What's the superior ramen type?", subtitle: "Broth wars", tags: ["food", "japanese", "ramen"], options: ["Tonkotsu", "Shoyu", "Miso", "Shio"] },
    { prompt: "Best melting cheese?", tags: ["food", "cheese"], options: ["Cheddar", "Mozzarella", "Gruyere", "American"] },
    { prompt: "Which regional BBQ style reigns supreme?", tags: ["food", "bbq"], options: ["Texas", "Kansas City", "Carolina", "Memphis"] },
    { prompt: "Best classic ice cream flavor?", tags: ["food", "dessert"], options: ["Vanilla", "Chocolate", "Strawberry", "Mint chip"] },
    { prompt: "What's the best way to cook eggs?", subtitle: "The breakfast fundamental", tags: ["food", "breakfast", "eggs"], options: ["Scrambled", "Over easy", "Poached", "Omelet"] },
    { prompt: "Best sandwich bread?", tags: ["food", "bread"], options: ["Sourdough", "Ciabatta", "Rye", "Brioche"] },
    { prompt: "Which food city is actually the best?", tags: ["food", "cities"], options: ["Tokyo", "Paris", "Mexico City", "Bangkok"] },
    { prompt: "Best fried chicken chain?", subtitle: "The ultimate ranking", tags: ["food", "fast-food", "chicken"], options: ["Popeyes", "Chick-fil-A", "KFC", "Raising Cane's"] },
    { prompt: "What's the superior pasta shape?", tags: ["food", "italian", "pasta"], options: ["Penne", "Rigatoni", "Spaghetti", "Fusilli"] },
    { prompt: "Best hot sauce?", tags: ["food", "condiments", "spicy"], options: ["Sriracha", "Tabasco", "Cholula", "Frank's RedHot"] },
    { prompt: "What's the best bagel?", subtitle: "Morning carbs debate", tags: ["food", "breakfast", "bread"], options: ["Everything", "Sesame", "Plain", "Cinnamon raisin"] },
    { prompt: "Best donut?", tags: ["food", "dessert", "breakfast"], options: ["Glazed", "Boston cream", "Jelly-filled", "Old fashioned"] },
    { prompt: "What's the superior wing sauce?", tags: ["food", "chicken", "spicy"], options: ["Buffalo", "BBQ", "Lemon pepper", "Garlic parmesan"] },
    { prompt: "Best steak doneness?", subtitle: "The line in the sand", tags: ["food", "steak"], options: ["Rare", "Medium rare", "Medium", "Medium well"] },
    { prompt: "What's the best sushi roll?", tags: ["food", "japanese", "sushi"], options: ["Spicy tuna", "California", "Dragon", "Rainbow"] },
    { prompt: "Best cookie?", subtitle: "The dessert classic", tags: ["food", "dessert"], options: ["Chocolate chip", "Oatmeal raisin", "Peanut butter", "Snickerdoodle"] },
    { prompt: "What's the superior french fry cut?", tags: ["food", "fast-food"], options: ["Shoestring", "Steak fries", "Crinkle cut", "Waffle fries"] },
    { prompt: "Best pizza topping?", tags: ["food", "pizza"], options: ["Pepperoni", "Mushrooms", "Sausage", "Pineapple"] },
    { prompt: "What's the best comfort food?", subtitle: "When you need a hug in food form", tags: ["food", "comfort"], options: ["Mac & cheese", "Fried chicken", "Mashed potatoes", "Grilled cheese"] },
    { prompt: "Best cheese for a burger?", tags: ["food", "burger", "cheese"], options: ["American", "Cheddar", "Swiss", "Blue cheese"] },
    { prompt: "What's the superior grain bowl base?", tags: ["food", "healthy"], options: ["Rice", "Quinoa", "Farro", "Couscous"] },
    { prompt: "Best taco shell?", subtitle: "Texture matters", tags: ["food", "mexican"], options: ["Soft corn", "Soft flour", "Hard shell", "Tostada"] },
    { prompt: "What's the best pie?", tags: ["food", "dessert"], options: ["Apple", "Pumpkin", "Pecan", "Key lime"] },
    { prompt: "Best dumpling?", tags: ["food", "asian"], options: ["Gyoza", "Xiao long bao", "Potstickers", "Pierogi"] },
    { prompt: "What's the superior cereal?", subtitle: "Saturday morning throwback", tags: ["food", "breakfast"], options: ["Frosted Flakes", "Cinnamon Toast Crunch", "Lucky Charms", "Honey Nut Cheerios"] },
    { prompt: "Best burrito style?", tags: ["food", "mexican"], options: ["Mission-style", "California burrito", "Breakfast burrito", "Chimichanga"] },
    { prompt: "What's the best cheese for pizza?", tags: ["food", "pizza", "cheese"], options: ["Fresh mozzarella", "Low-moisture mozzarella", "Provolone", "Blend"] },
    { prompt: "Best noodle soup?", subtitle: "The ultimate comfort bowl", tags: ["food", "soup"], options: ["Pho", "Ramen", "Chicken noodle", "Udon"] },
    { prompt: "What's the superior sandwich?", tags: ["food", "sandwich"], options: ["BLT", "Club", "Reuben", "Cheesesteak"] },
    { prompt: "Best potato preparation?", tags: ["food"], options: ["Fries", "Baked", "Mashed", "Hash browns"] },
    { prompt: "What's the best street food?", subtitle: "The people's cuisine", tags: ["food", "street-food"], options: ["Tacos", "Banh mi", "Kebab", "Hot dogs"] },
    { prompt: "Best brunch drink?", tags: ["food", "brunch", "drinks"], options: ["Mimosa", "Bloody Mary", "Bellini", "Irish coffee"] },
    { prompt: "What's the superior dipping sauce for fries?", tags: ["food", "condiments"], options: ["Ketchup", "Mayo", "Ranch", "Aioli"] },
    { prompt: "Best cake flavor?", tags: ["food", "dessert"], options: ["Chocolate", "Vanilla", "Red velvet", "Carrot"] },
    { prompt: "What's the best way to eat potatoes at breakfast?", subtitle: "Morning spud showdown", tags: ["food", "breakfast"], options: ["Hash browns", "Home fries", "Tater tots", "Rosti"] },
    { prompt: "Best Asian noodle?", tags: ["food", "asian", "noodles"], options: ["Rice noodles", "Udon", "Soba", "Ramen noodles"] },
    { prompt: "What's the superior grilled meat?", tags: ["food", "bbq"], options: ["Ribeye steak", "Pork ribs", "Chicken thighs", "Lamb chops"] },
    { prompt: "Best breakfast meat?", tags: ["food", "breakfast"], options: ["Bacon", "Sausage", "Ham", "Scrapple"] },
    { prompt: "What's the best drunk pizza order?", subtitle: "2 AM decisions", tags: ["food", "pizza", "late-night"], options: ["Plain cheese", "Pepperoni", "Hawaiian", "Everything"] },
    { prompt: "Best gas station snack?", tags: ["food", "snacks"], options: ["Beef jerky", "Combos", "Slim Jim", "Hot Cheetos"] },
    { prompt: "What's the superior deli meat?", tags: ["food", "sandwich"], options: ["Turkey", "Roast beef", "Ham", "Salami"] },
    { prompt: "Best sauce for pasta?", subtitle: "The Italian question", tags: ["food", "italian", "pasta"], options: ["Marinara", "Carbonara", "Alfredo", "Bolognese"] },
    { prompt: "What's the best movie theater snack?", tags: ["food", "snacks"], options: ["Popcorn", "Nachos", "Candy", "Hot dog"] },
    { prompt: "Best breakfast carb?", tags: ["food", "breakfast"], options: ["Toast", "Bagel", "English muffin", "Croissant"] },
    { prompt: "What's the superior wing style?", tags: ["food", "chicken"], options: ["Traditional Buffalo", "Boneless", "Korean fried", "Dry rub"] },
    { prompt: "Best way to eat rice?", subtitle: "The staple debate", tags: ["food", "rice"], options: ["Fried rice", "Steamed white", "Risotto", "Pilaf"] },
    { prompt: "What's the best drunk food chain?", tags: ["food", "fast-food", "late-night"], options: ["Taco Bell", "Waffle House", "White Castle", "Jack in the Box"] },
    { prompt: "Best chocolate candy?", tags: ["food", "dessert", "candy"], options: ["Reese's", "Snickers", "Kit Kat", "Twix"] },
    { prompt: "What's the superior soup?", tags: ["food", "soup"], options: ["Tomato", "Chicken noodle", "Clam chowder", "French onion"] },
    { prompt: "Best food to share?", subtitle: "Peak communal eating", tags: ["food"], options: ["Pizza", "Wings", "Nachos", "Chips & guac"] },
    { prompt: "What's the best Michelin experience vs hole-in-the-wall?", tags: ["food", "dining"], options: ["Michelin 3-star", "Hole-in-the-wall", "Food truck", "Hometown diner"] },
    { prompt: "Best bread for toast?", tags: ["food", "breakfast", "bread"], options: ["Sourdough", "Whole wheat", "White bread", "Rye"] },
    { prompt: "What's the superior breakfast potato dish?", subtitle: "Carbs in the morning", tags: ["food", "breakfast"], options: ["Hash browns", "Home fries", "Breakfast burrito potatoes", "Latkes"] },
  ],
  movies: [
    { prompt: "Who played Batman best?", subtitle: "The definitive Dark Knight", tags: ["movies", "superhero", "casting"], options: ["Christian Bale", "Michael Keaton", "Ben Affleck", "Robert Pattinson"] },
    { prompt: "Who played Spider-Man best?", tags: ["movies", "superhero", "casting"], options: ["Tobey Maguire", "Andrew Garfield", "Tom Holland"] },
    { prompt: "What's the best movie trilogy?", subtitle: "Three's company", tags: ["movies", "franchise"], options: ["The Lord of the Rings", "The Dark Knight", "Back to the Future", "The Godfather"] },
    { prompt: "What's the best Pixar movie?", tags: ["movies", "animation", "pixar"], options: ["Toy Story", "Up", "Inside Out", "WALL-E"] },
    { prompt: "What's the scariest horror movie?", subtitle: "Sleep with the lights on", tags: ["movies", "horror"], options: ["The Exorcist", "The Shining", "Hereditary", "The Texas Chain Saw Massacre"] },
    { prompt: "What's the best Tarantino movie?", tags: ["movies", "director", "tarantino"], options: ["Pulp Fiction", "Django Unchained", "Kill Bill", "Reservoir Dogs"] },
    { prompt: "Who's the greatest movie villain?", subtitle: "Pure evil on screen", tags: ["movies", "villain", "character"], options: ["Darth Vader", "The Joker", "Hannibal Lecter", "Anton Chigurh"] },
    { prompt: "What's the best film of the 21st century?", tags: ["movies", "decade"], options: ["The Lord of the Rings: Return of the King", "There Will Be Blood", "Parasite", "No Country for Old Men"] },
    { prompt: "Who played James Bond best?", subtitle: "Shaken, not stirred", tags: ["movies", "casting", "franchise"], options: ["Sean Connery", "Daniel Craig", "Pierce Brosnan", "Roger Moore"] },
    { prompt: "Who played the Joker best?", tags: ["movies", "superhero", "villain", "casting"], options: ["Heath Ledger", "Joaquin Phoenix", "Jack Nicholson", "Mark Hamill"] },
    { prompt: "What's the best Christopher Nolan movie?", tags: ["movies", "director", "nolan"], options: ["The Dark Knight", "Inception", "Interstellar", "The Prestige"] },
    { prompt: "What's the best Martin Scorsese movie?", subtitle: "The master of cinema", tags: ["movies", "director", "scorsese"], options: ["Goodfellas", "Taxi Driver", "The Departed", "Raging Bull"] },
    { prompt: "What's the best Steven Spielberg movie?", tags: ["movies", "director", "spielberg"], options: ["Schindler's List", "Jaws", "Jurassic Park", "Saving Private Ryan"] },
    { prompt: "Who played Superman best?", tags: ["movies", "superhero", "casting"], options: ["Christopher Reeve", "Henry Cavill", "Brandon Routh", "Tyler Hoechlin"] },
    { prompt: "What's the best Stanley Kubrick movie?", subtitle: "Visionary perfectionist", tags: ["movies", "director", "kubrick"], options: ["2001: A Space Odyssey", "The Shining", "A Clockwork Orange", "Full Metal Jacket"] },
    { prompt: "What's the best movie decade?", tags: ["movies", "decade", "era"], options: ["1970s", "1980s", "1990s", "2010s"] },
    { prompt: "What's the best heist movie?", subtitle: "The perfect crime", tags: ["movies", "genre", "heist"], options: ["Ocean's Eleven", "Heat", "The Italian Job", "Inception"] },
    { prompt: "What's the best movie soundtrack?", tags: ["movies", "music", "soundtrack"], options: ["Pulp Fiction", "Guardians of the Galaxy", "The Graduate", "Trainspotting"] },
    { prompt: "What's the best movie score?", subtitle: "Pure instrumental magic", tags: ["movies", "music", "score"], options: ["Star Wars", "The Lord of the Rings", "Inception", "Interstellar"] },
    { prompt: "What's the best plot twist?", tags: ["movies", "twist", "screenplay"], options: ["The Sixth Sense", "The Usual Suspects", "Fight Club", "The Prestige"] },
    { prompt: "What's the best opening scene?", subtitle: "Hook them from frame one", tags: ["movies", "scene", "opening"], options: ["The Dark Knight", "Inglourious Basterds", "Saving Private Ryan", "Up"] },
    { prompt: "What's the best final scene?", tags: ["movies", "scene", "ending"], options: ["The Shawshank Redemption", "Inception", "The Godfather", "Whiplash"] },
    { prompt: "What's the best movie monologue?", subtitle: "One person, center stage", tags: ["movies", "scene", "monologue"], options: ["Jaws USS Indianapolis", "Network 'Mad as Hell'", "Good Will Hunting bench", "Blade Runner Tears in Rain"] },
    { prompt: "What's the best fight scene?", tags: ["movies", "action", "choreography"], options: ["The Matrix lobby", "John Wick nightclub", "Oldboy hallway", "The Raid apartment"] },
    { prompt: "What's the best romantic comedy?", subtitle: "Love and laughs", tags: ["movies", "genre", "romance", "comedy"], options: ["When Harry Met Sally", "The Princess Bride", "Crazy, Stupid, Love", "10 Things I Hate About You"] },
    { prompt: "What's the best sci-fi movie?", tags: ["movies", "genre", "scifi"], options: ["Blade Runner", "2001: A Space Odyssey", "The Matrix", "Arrival"] },
    { prompt: "What's the best war movie?", subtitle: "Hell on earth", tags: ["movies", "genre", "war"], options: ["Apocalypse Now", "Saving Private Ryan", "Full Metal Jacket", "Dunkirk"] },
    { prompt: "What's the best animated movie?", tags: ["movies", "animation", "genre"], options: ["Spirited Away", "The Lion King", "Spider-Man: Into the Spider-Verse", "WALL-E"] },
    { prompt: "Animation studio supremacy?", subtitle: "Who owns the game", tags: ["movies", "animation", "studio"], options: ["Pixar", "Studio Ghibli", "Disney Animation", "DreamWorks"] },
    { prompt: "What's the best sports movie?", tags: ["movies", "genre", "sports"], options: ["Rocky", "Raging Bull", "Moneyball", "Hoosiers"] },
    { prompt: "What's the best biopic?", subtitle: "Based on a true story", tags: ["movies", "genre", "biopic"], options: ["Raging Bull", "The Social Network", "Walk the Line", "Bohemian Rhapsody"] },
    { prompt: "What's the best Western?", tags: ["movies", "genre", "western"], options: ["The Good, the Bad and the Ugly", "Unforgiven", "No Country for Old Men", "True Grit"] },
    { prompt: "What's the best comedy?", subtitle: "Pure laughs", tags: ["movies", "genre", "comedy"], options: ["Airplane!", "The Big Lebowski", "Superbad", "Groundhog Day"] },
    { prompt: "What's the best thriller?", tags: ["movies", "genre", "thriller"], options: ["Se7en", "Silence of the Lambs", "Zodiac", "Prisoners"] },
    { prompt: "What's the best documentary?", subtitle: "Truth stranger than fiction", tags: ["movies", "documentary", "genre"], options: ["Won't You Be My Neighbor?", "Free Solo", "The Act of Killing", "13th"] },
    { prompt: "Remake vs. Original?", tags: ["movies", "remake"], options: ["Original always wins", "Some remakes are better", "Depends on the film"] },
    { prompt: "What's the best movie snack?", subtitle: "Theater essentials", tags: ["movies", "food", "experience"], options: ["Popcorn", "Candy", "Nachos", "Nothing, just watch"] },
    { prompt: "Theater vs. streaming?", tags: ["movies", "experience", "viewing"], options: ["Theater experience", "Streaming at home", "Depends on the movie"] },
    { prompt: "What's the best film festival?", subtitle: "Where cinema lives", tags: ["movies", "festival", "industry"], options: ["Cannes", "Sundance", "Venice", "Toronto"] },
    { prompt: "Biggest Oscar snub?", tags: ["movies", "oscars", "awards"], options: ["The Shawshank Redemption", "Goodfellas", "The Dark Knight", "Pulp Fiction"] },
    { prompt: "What's the best car chase?", subtitle: "Pedal to the metal", tags: ["movies", "action", "chase"], options: ["Bullitt", "Mad Max: Fury Road", "The French Connection", "Baby Driver"] },
    { prompt: "What's the best ensemble cast?", tags: ["movies", "casting", "ensemble"], options: ["The Lord of the Rings", "Pulp Fiction", "Ocean's Eleven", "The Grand Budapest Hotel"] },
    { prompt: "What's the best buddy cop movie?", subtitle: "Partners in crime-fighting", tags: ["movies", "genre", "action", "comedy"], options: ["Lethal Weapon", "Bad Boys", "Hot Fuzz", "Rush Hour"] },
    { prompt: "What's the best prison movie?", tags: ["movies", "genre", "prison"], options: ["The Shawshank Redemption", "The Green Mile", "Cool Hand Luke", "Escape from Alcatraz"] },
    { prompt: "What's the best courtroom drama?", subtitle: "Order in the court", tags: ["movies", "genre", "drama", "legal"], options: ["12 Angry Men", "A Few Good Men", "To Kill a Mockingbird", "The Verdict"] },
    { prompt: "What's the best coming-of-age film?", tags: ["movies", "genre", "drama"], options: ["Stand by Me", "Lady Bird", "Boyhood", "The Breakfast Club"] },
    { prompt: "What's the best dystopian movie?", subtitle: "Nightmare futures", tags: ["movies", "genre", "scifi", "dystopia"], options: ["Brazil", "Children of Men", "Mad Max: Fury Road", "1984"] },
    { prompt: "What's the best one-liner?", tags: ["movies", "quotes", "dialogue"], options: ["I'll be back", "Here's looking at you, kid", "May the Force be with you", "You talking to me?"] },
    { prompt: "What's the best movie poster?", subtitle: "Visual marketing art", tags: ["movies", "design", "marketing"], options: ["Jaws", "Star Wars", "The Shining", "Pulp Fiction"] },
    { prompt: "What's the best Christmas movie?", tags: ["movies", "holiday", "christmas"], options: ["Die Hard", "It's a Wonderful Life", "Home Alone", "Elf"] },
    { prompt: "What's the best superhero movie?", subtitle: "Heroes rise", tags: ["movies", "superhero", "genre"], options: ["The Dark Knight", "Logan", "Spider-Man: Into the Spider-Verse", "The Avengers"] },
    { prompt: "What's the best movie franchise?", tags: ["movies", "franchise"], options: ["Star Wars", "Marvel Cinematic Universe", "The Lord of the Rings", "Mission: Impossible"] },
    { prompt: "What's the most quotable movie?", subtitle: "Every line is gold", tags: ["movies", "quotes", "dialogue"], options: ["The Princess Bride", "Mean Girls", "Anchorman", "The Big Lebowski"] },
    { prompt: "What's the best use of color?", tags: ["movies", "cinematography", "visual"], options: ["The Grand Budapest Hotel", "In the Mood for Love", "Mad Max: Fury Road", "Hero"] },
    { prompt: "What's the best long take?", subtitle: "No cuts, just skill", tags: ["movies", "cinematography", "technique"], options: ["1917 opening", "Goodfellas Copacabana", "Children of Men car", "True Detective Episode 4"] },
    { prompt: "What's the best movie trailer?", tags: ["movies", "marketing", "trailer"], options: ["Inception", "The Social Network", "Mad Max: Fury Road", "Logan"] },
    { prompt: "What's the best movie cameo?", subtitle: "Surprise appearances", tags: ["movies", "casting", "cameo"], options: ["Bill Murray in Zombieland", "Tom Cruise in Tropic Thunder", "Stan Lee in Marvel movies", "Matt Damon in Interstellar"] },
    { prompt: "What's the best disaster movie?", tags: ["movies", "genre", "disaster"], options: ["Twister", "The Day After Tomorrow", "2012", "The Towering Inferno"] },
    { prompt: "What's the best musical?", subtitle: "Sing and dance", tags: ["movies", "genre", "musical"], options: ["Singin' in the Rain", "La La Land", "The Sound of Music", "West Side Story"] },
    { prompt: "What's the best drug movie?", tags: ["movies", "genre", "drugs"], options: ["Requiem for a Dream", "Trainspotting", "Fear and Loathing in Las Vegas", "Blow"] },
    { prompt: "Best director of all time?", subtitle: "Behind the camera legends", tags: ["movies", "director"], options: ["Stanley Kubrick", "Martin Scorsese", "Steven Spielberg", "Alfred Hitchcock"] },
    { prompt: "Best cinematographer of all time?", tags: ["movies", "cinematography"], options: ["Roger Deakins", "Emmanuel Lubezki", "Robert Richardson", "Vittorio Storaro"] },
    { prompt: "What actor had the best run?", subtitle: "Peak performance era", tags: ["movies", "casting", "actor"], options: ["Leonardo DiCaprio 2010s", "Denzel Washington 1990s", "Tom Hanks 1990s", "Daniel Day-Lewis 2000s"] },
    { prompt: "What's the most overrated movie?", tags: ["movies", "hot-take"], options: ["The Godfather", "Citizen Kane", "Avatar", "Forrest Gump"] },
    { prompt: "What's the most underrated movie?", subtitle: "Hidden gems", tags: ["movies", "hot-take"], options: ["The Prestige", "Children of Men", "The Iron Giant", "Kiss Kiss Bang Bang"] },
  ],
  tv: [
    { prompt: "What's the greatest TV drama of all time?", subtitle: "The heavyweights of prestige television", tags: ["tv", "drama"], options: ["The Sopranos", "The Wire", "Breaking Bad", "Mad Men"] },
    { prompt: "What's the greatest sitcom of all time?", subtitle: "Comedy royalty", tags: ["tv", "comedy"], options: ["Seinfeld", "The Office", "Friends", "Arrested Development"] },
    { prompt: "What's the best TV theme song?", tags: ["tv", "music"], options: ["The Fresh Prince of Bel-Air", "Cheers", "Game of Thrones", "The Simpsons"] },
    { prompt: "What's the best adult animated series?", tags: ["tv", "animation"], options: ["The Simpsons", "South Park", "Rick and Morty", "BoJack Horseman"] },
    { prompt: "What's the best reality TV show?", subtitle: "Guilty pleasures welcome", tags: ["tv", "reality"], options: ["Survivor", "The Bachelor", "RuPaul's Drag Race", "Top Chef"] },
    { prompt: "What's the best TV series finale?", tags: ["tv", "finale"], options: ["Breaking Bad", "The Good Place", "Six Feet Under", "The Americans"] },
    { prompt: "Who's the greatest TV villain?", tags: ["tv", "characters"], options: ["Joffrey Baratheon", "Walter White", "The Night King", "Gus Fring"] },
    { prompt: "What's the best limited series?", subtitle: "One season wonders", tags: ["tv", "limited-series"], options: ["Chernobyl", "The Queen's Gambit", "Mare of Easttown", "Watchmen"] },
    { prompt: "What's the best TV couple?", tags: ["tv", "romance"], options: ["Jim and Pam", "Ross and Rachel", "Homer and Marge", "Leslie and Ben"] },
    { prompt: "What show has the best cold opens?", subtitle: "Before the theme song hits", tags: ["tv", "comedy"], options: ["The Office", "Brooklyn Nine-Nine", "Community", "30 Rock"] },
    { prompt: "What's the best bottle episode?", tags: ["tv", "episodes"], options: ["Fly (Breaking Bad)", "Cooperative Calligraphy (Community)", "The Chinese Restaurant (Seinfeld)", "Pine Barrens (The Sopranos)"] },
    { prompt: "What's the best TV spin-off?", tags: ["tv", "spin-offs"], options: ["Frasier", "Better Call Saul", "The Jeffersons", "Mork & Mindy"] },
    { prompt: "What's the most disappointing series finale?", subtitle: "They fumbled the ending", tags: ["tv", "finale"], options: ["Game of Thrones", "Dexter", "How I Met Your Mother", "Lost"] },
    { prompt: "Who's the best TV dad?", tags: ["tv", "characters"], options: ["Uncle Phil", "Homer Simpson", "Dan Conner", "Cliff Huxtable"] },
    { prompt: "Who's the best TV mom?", tags: ["tv", "characters"], options: ["Claire Huxtable", "Lorelai Gilmore", "Morticia Addams", "Marge Simpson"] },
    { prompt: "What's the best workplace comedy?", tags: ["tv", "comedy"], options: ["The Office", "Parks and Recreation", "30 Rock", "Scrubs"] },
    { prompt: "What's the best crime procedural?", subtitle: "Law and order in TV form", tags: ["tv", "crime"], options: ["Law & Order", "CSI", "Criminal Minds", "NCIS"] },
    { prompt: "What's the best sci-fi series?", tags: ["tv", "sci-fi"], options: ["Star Trek: The Next Generation", "The X-Files", "Battlestar Galactica", "Black Mirror"] },
    { prompt: "What's the best fantasy series?", tags: ["tv", "fantasy"], options: ["Game of Thrones", "The Witcher", "Buffy the Vampire Slayer", "The Lord of the Rings: The Rings of Power"] },
    { prompt: "What's the best teen drama?", subtitle: "High school never felt so dramatic", tags: ["tv", "teen"], options: ["The O.C.", "Gossip Girl", "Dawson's Creek", "Friday Night Lights"] },
    { prompt: "What's the best medical drama?", tags: ["tv", "medical"], options: ["Grey's Anatomy", "ER", "House", "Scrubs"] },
    { prompt: "What's the best legal drama?", tags: ["tv", "legal"], options: ["The Practice", "Suits", "Boston Legal", "Better Call Saul"] },
    { prompt: "What's the best pilot episode?", subtitle: "Strong first impressions", tags: ["tv", "episodes"], options: ["Lost", "Breaking Bad", "The West Wing", "Friday Night Lights"] },
    { prompt: "What show has the best ensemble cast?", tags: ["tv", "characters"], options: ["Friends", "Community", "The West Wing", "Arrested Development"] },
    { prompt: "What's the best TV reboot?", tags: ["tv", "reboots"], options: ["Battlestar Galactica", "Westworld", "Doctor Who (2005)", "Fuller House"] },
    { prompt: "Who's the best late night talk show host?", subtitle: "The masters of monologues", tags: ["tv", "talk-shows"], options: ["David Letterman", "Johnny Carson", "Conan O'Brien", "Jon Stewart"] },
    { prompt: "What's the best Netflix original series?", tags: ["tv", "streaming"], options: ["Stranger Things", "The Crown", "Ozark", "Orange is the New Black"] },
    { prompt: "What's the best British comedy?", tags: ["tv", "british", "comedy"], options: ["The Office (UK)", "Fleabag", "Peep Show", "The IT Crowd"] },
    { prompt: "What's the best anime series?", subtitle: "The cream of the crop", tags: ["tv", "anime"], options: ["Death Note", "Attack on Titan", "Cowboy Bebop", "Fullmetal Alchemist: Brotherhood"] },
    { prompt: "What's the best cooking competition show?", tags: ["tv", "cooking", "competition"], options: ["Top Chef", "MasterChef", "The Great British Bake Off", "Iron Chef"] },
    { prompt: "What's the best game show?", tags: ["tv", "game-shows"], options: ["Jeopardy!", "Wheel of Fortune", "The Price is Right", "Who Wants to Be a Millionaire"] },
    { prompt: "What's the best TV bromance?", tags: ["tv", "characters"], options: ["Turk and J.D.", "Chandler and Joey", "Shawn and Gus", "Troy and Abed"] },
    { prompt: "What decade had the best TV?", subtitle: "Peak television by era", tags: ["tv", "decades"], options: ["1990s", "2000s", "2010s", "1980s"] },
    { prompt: "Who's the best TV anti-hero?", tags: ["tv", "characters"], options: ["Tony Soprano", "Walter White", "Don Draper", "Dexter Morgan"] },
    { prompt: "What's the best Saturday Night Live cast?", subtitle: "Peak SNL lineups", tags: ["tv", "comedy"], options: ["1975-1980 (Original)", "1988-1995 (Sandler/Farley era)", "2008-2012 (Wiig/Samberg era)", "1997-2002 (Ferrell/Fey era)"] },
    { prompt: "What's the best TV Christmas episode?", tags: ["tv", "episodes", "holidays"], options: ["The Office (Moroccan Christmas)", "Friends (The One with the Holiday Armadillo)", "Community (Abed's Uncontrollable Christmas)", "The O.C. (The Best Chrismukkah Ever)"] },
    { prompt: "What's the best TV detective?", tags: ["tv", "characters", "crime"], options: ["Sherlock Holmes (Sherlock)", "Columbo", "Jessica Fletcher", "Adrian Monk"] },
    { prompt: "What's the best TV musical episode?", subtitle: "When regular shows break into song", tags: ["tv", "episodes", "music"], options: ["Once More, With Feeling (Buffy)", "My Musical (Scrubs)", "Schmigadoon!", "The Nightman Cometh (It's Always Sunny)"] },
    { prompt: "What's the best HBO drama?", tags: ["tv", "drama", "hbo"], options: ["The Sopranos", "The Wire", "Game of Thrones", "Succession"] },
    { prompt: "What's the best character transformation?", subtitle: "The ultimate character arcs", tags: ["tv", "characters"], options: ["Walter White (Breaking Bad)", "Zuko (Avatar)", "Steve Harrington (Stranger Things)", "Jamie Lannister (Game of Thrones)"] },
    { prompt: "What's the best TV rivalry?", tags: ["tv", "characters"], options: ["Bart vs. Sideshow Bob", "Jack vs. Locke", "Jimmy vs. Chuck", "Dwight vs. Jim"] },
    { prompt: "What's the best competition reality show?", tags: ["tv", "reality", "competition"], options: ["The Amazing Race", "Project Runway", "RuPaul's Drag Race", "The Voice"] },
    { prompt: "What's the best TV opening credits sequence?", subtitle: "The art of the intro", tags: ["tv", "music"], options: ["True Detective (Season 1)", "Westworld", "Succession", "Game of Thrones"] },
    { prompt: "What's the best TV documentary series?", tags: ["tv", "documentary"], options: ["Planet Earth", "Making a Murderer", "The Last Dance", "Tiger King"] },
    { prompt: "What's the best kids' show for adults?", tags: ["tv", "animation"], options: ["Avatar: The Last Airbender", "Bluey", "Adventure Time", "Gravity Falls"] },
    { prompt: "What's the most quotable TV show?", subtitle: "Lines you use in daily life", tags: ["tv", "comedy"], options: ["The Office", "Seinfeld", "The Simpsons", "Arrested Development"] },
    { prompt: "What's the best TV show cancelled too soon?", tags: ["tv", "cancelled"], options: ["Firefly", "Freaks and Geeks", "Arrested Development", "My So-Called Life"] },
    { prompt: "Who's the best TV sidekick?", tags: ["tv", "characters"], options: ["Samwise Gamgee", "Robin (Batman)", "Dr. Watson", "Dwight Schrute"] },
    { prompt: "What's the best period drama?", tags: ["tv", "drama", "period"], options: ["Mad Men", "The Crown", "Downton Abbey", "Peaky Blinders"] },
    { prompt: "What's the best TV show about TV?", subtitle: "Meta television at its finest", tags: ["tv", "comedy"], options: ["30 Rock", "The Larry Sanders Show", "BoJack Horseman", "The Comeback"] },
    { prompt: "What's the best Apple TV+ original?", tags: ["tv", "streaming"], options: ["Ted Lasso", "Severance", "The Morning Show", "For All Mankind"] },
    { prompt: "What's the best TV cliffhanger?", tags: ["tv", "episodes"], options: ["Who shot J.R.? (Dallas)", "We have to go back! (Lost)", "Season 3 finale (The Good Place)", "Ozymandias (Breaking Bad)"] },
    { prompt: "What's the best Amazon Prime original?", tags: ["tv", "streaming"], options: ["The Boys", "The Marvelous Mrs. Maisel", "Fleabag", "Reacher"] },
    { prompt: "What's the best TV courtroom drama?", tags: ["tv", "legal", "drama"], options: ["The Good Wife", "Law & Order", "Perry Mason", "Ally McBeal"] },
    { prompt: "What's the best TV western?", tags: ["tv", "western"], options: ["Deadwood", "Justified", "Westworld", "Yellowstone"] },
    { prompt: "What's the best TV show based on a book?", tags: ["tv", "adaptations"], options: ["Game of Thrones", "The Handmaid's Tale", "Big Little Lies", "The Queen's Gambit"] },
    { prompt: "What's the best horror TV series?", subtitle: "Nightmares on the small screen", tags: ["tv", "horror"], options: ["The Walking Dead", "American Horror Story", "The Haunting of Hill House", "Stranger Things"] },
    { prompt: "What's the best TV episode of all time?", tags: ["tv", "episodes"], options: ["Ozymandias (Breaking Bad)", "The Constant (Lost)", "International Assassin (The Leftovers)", "Two Cathedrals (The West Wing)"] },
    { prompt: "What's the best TV show set in high school?", tags: ["tv", "teen"], options: ["Freaks and Geeks", "Buffy the Vampire Slayer", "Saved by the Bell", "Degrassi"] },
    { prompt: "What's the best streaming service for original content?", subtitle: "The streaming wars winner", tags: ["tv", "streaming"], options: ["Netflix", "HBO Max", "Disney+", "Apple TV+"] },
    { prompt: "What's the best British drama?", tags: ["tv", "british", "drama"], options: ["Sherlock", "The Crown", "Peaky Blinders", "Broadchurch"] },
  ],
  sports: [
    { prompt: "Who's the basketball GOAT?", subtitle: "The eternal debate", tags: ["sports", "basketball"], options: ["Michael Jordan", "LeBron James", "Kareem Abdul-Jabbar", "Kobe Bryant"] },
    { prompt: "Who's the soccer GOAT?", subtitle: "The beautiful game's finest", tags: ["sports", "soccer"], options: ["Lionel Messi", "Cristiano Ronaldo", "Pele", "Diego Maradona"] },
    { prompt: "What's the best Olympic sport to watch?", tags: ["sports", "olympics"], options: ["Gymnastics", "Swimming", "Track & Field", "Basketball"] },
    { prompt: "Who's the greatest athlete of all time?", subtitle: "Cross-sport dominance", tags: ["sports", "general"], options: ["Michael Jordan", "Serena Williams", "Muhammad Ali", "Usain Bolt"] },
    { prompt: "Who's the best NFL quarterback ever?", tags: ["sports", "football"], options: ["Tom Brady", "Joe Montana", "Peyton Manning", "Patrick Mahomes"] },
    { prompt: "What's the greatest sports rivalry?", tags: ["sports", "rivalries"], options: ["Lakers vs. Celtics", "Yankees vs. Red Sox", "Federer vs. Nadal", "Ali vs. Frazier"] },
    { prompt: "Who's the tennis GOAT?", subtitle: "Men's edition", tags: ["sports", "tennis"], options: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"] },
    { prompt: "What's the most exciting sport to watch?", tags: ["sports", "general"], options: ["Football (Soccer)", "Basketball", "American Football", "Hockey"] },
    { prompt: "Who's the greatest boxer of all time?", subtitle: "Pound for pound", tags: ["sports", "boxing"], options: ["Muhammad Ali", "Mike Tyson", "Sugar Ray Robinson", "Floyd Mayweather"] },
    { prompt: "What's the best position in basketball?", tags: ["sports", "basketball"], options: ["Point Guard", "Shooting Guard", "Small Forward", "Center"] },
    { prompt: "Who's the best running back ever?", tags: ["sports", "football"], options: ["Jim Brown", "Walter Payton", "Barry Sanders", "Emmitt Smith"] },
    { prompt: "What's the greatest baseball team of all time?", tags: ["sports", "baseball"], options: ["1927 Yankees", "1998 Yankees", "Big Red Machine", "2016 Cubs"] },
    { prompt: "Who's the hockey GOAT?", subtitle: "The Great One debate", tags: ["sports", "hockey"], options: ["Wayne Gretzky", "Mario Lemieux", "Bobby Orr", "Gordie Howe"] },
    { prompt: "What's the most difficult sport to master?", tags: ["sports", "general"], options: ["Golf", "Baseball", "Cricket", "Tennis"] },
    { prompt: "Who's the greatest golfer ever?", tags: ["sports", "golf"], options: ["Tiger Woods", "Jack Nicklaus", "Arnold Palmer", "Ben Hogan"] },
    { prompt: "What's the best Formula 1 team in history?", subtitle: "Racing royalty", tags: ["sports", "racing"], options: ["Ferrari", "McLaren", "Mercedes", "Red Bull Racing"] },
    { prompt: "Who's the greatest F1 driver of all time?", tags: ["sports", "racing"], options: ["Ayrton Senna", "Michael Schumacher", "Lewis Hamilton", "Juan Manuel Fangio"] },
    { prompt: "What's the best Super Bowl halftime show?", tags: ["sports", "football", "entertainment"], options: ["Prince (2007)", "Beyonce (2013)", "The Weeknd (2021)", "Shakira & J.Lo (2020)"] },
    { prompt: "Who's the greatest sprinter ever?", subtitle: "Pure speed", tags: ["sports", "track"], options: ["Usain Bolt", "Carl Lewis", "Jesse Owens", "Florence Griffith-Joyner"] },
    { prompt: "What's the most iconic World Cup moment?", tags: ["sports", "soccer"], options: ["Maradona's Hand of God", "Zidane's Headbutt", "Brazil's 7-1 Loss", "Pele's 1970 Performance"] },
    { prompt: "Who's the greatest swimmer of all time?", tags: ["sports", "swimming"], options: ["Michael Phelps", "Mark Spitz", "Katie Ledecky", "Ian Thorpe"] },
    { prompt: "What's the best sports movie ever made?", subtitle: "Hollywood's finest", tags: ["sports", "movies"], options: ["Rocky", "Hoosiers", "Remember the Titans", "Moneyball"] },
    { prompt: "Who's the greatest NBA dynasty?", tags: ["sports", "basketball"], options: ["90s Bulls", "60s Celtics", "80s Lakers", "2010s Warriors"] },
    { prompt: "What's the best soccer league in the world?", tags: ["sports", "soccer"], options: ["Premier League", "La Liga", "Serie A", "Bundesliga"] },
    { prompt: "Who's the best wide receiver ever?", tags: ["sports", "football"], options: ["Jerry Rice", "Randy Moss", "Terrell Owens", "Calvin Johnson"] },
    { prompt: "What's the greatest sports comeback of all time?", subtitle: "Against all odds", tags: ["sports", "general"], options: ["28-3 Super Bowl", "2016 NBA Finals", "Istanbul 2005 (Liverpool)", "Tiger's 2019 Masters"] },
    { prompt: "Who's the tennis GOAT (women's)?", tags: ["sports", "tennis"], options: ["Serena Williams", "Steffi Graf", "Martina Navratilova", "Margaret Court"] },
    { prompt: "What's the best Olympic moment ever?", tags: ["sports", "olympics"], options: ["Usain Bolt's Triple-Triple", "Miracle on Ice", "Jesse Owens 1936", "Michael Phelps 8 Golds"] },
    { prompt: "Who's the greatest MMA fighter?", subtitle: "Octagon legends", tags: ["sports", "mma"], options: ["Jon Jones", "Anderson Silva", "Georges St-Pierre", "Khabib Nurmagomedov"] },
    { prompt: "What's the best sports video game franchise?", tags: ["sports", "gaming"], options: ["FIFA/EA FC", "Madden NFL", "NBA 2K", "MLB The Show"] },
    { prompt: "Who's the greatest college basketball coach?", tags: ["sports", "basketball", "college"], options: ["John Wooden", "Mike Krzyzewski", "Dean Smith", "Roy Williams"] },
    { prompt: "What's the best baseball park in America?", subtitle: "Classic stadiums", tags: ["sports", "baseball"], options: ["Fenway Park", "Wrigley Field", "Dodger Stadium", "Oracle Park"] },
    { prompt: "Who's the greatest pitcher in baseball history?", tags: ["sports", "baseball"], options: ["Sandy Koufax", "Roger Clemens", "Greg Maddux", "Nolan Ryan"] },
    { prompt: "What's the most underrated sport?", tags: ["sports", "general"], options: ["Rugby", "Lacrosse", "Volleyball", "Handball"] },
    { prompt: "Who's the best NBA defender ever?", subtitle: "Lockdown legends", tags: ["sports", "basketball"], options: ["Michael Jordan", "Gary Payton", "Dennis Rodman", "Kawhi Leonard"] },
    { prompt: "What's the greatest sports dynasty ever?", tags: ["sports", "general"], options: ["Patriots (2000s-2010s)", "Yankees (1940s-1960s)", "Celtics (1960s)", "Canadiens (1950s-1970s)"] },
    { prompt: "Who's the most clutch athlete of all time?", tags: ["sports", "general"], options: ["Michael Jordan", "Tom Brady", "Derek Jeter", "Kobe Bryant"] },
    { prompt: "What's the best sports nickname?", subtitle: "Legendary monikers", tags: ["sports", "general"], options: ["Air Jordan", "The Great One", "His Airness", "The Black Mamba"] },
    { prompt: "Who's the greatest defensive player in NFL history?", tags: ["sports", "football"], options: ["Lawrence Taylor", "Reggie White", "Deion Sanders", "Ray Lewis"] },
    { prompt: "What's the best sports era to have lived through?", tags: ["sports", "general"], options: ["1980s", "1990s", "2000s", "2010s"] },
    { prompt: "Who's the greatest trash talker in sports?", subtitle: "Mind games", tags: ["sports", "general"], options: ["Muhammad Ali", "Larry Bird", "Michael Jordan", "Connor McGregor"] },
    { prompt: "What's the best college football program ever?", tags: ["sports", "football", "college"], options: ["Alabama", "Notre Dame", "Ohio State", "USC"] },
    { prompt: "Who's the best soccer player to never win a World Cup?", tags: ["sports", "soccer"], options: ["Johan Cruyff", "George Best", "Alfredo Di Stefano", "Zlatan Ibrahimovic"] },
    { prompt: "What's the most impressive individual season ever?", subtitle: "Peak performance", tags: ["sports", "general"], options: ["Wilt's 50 PPG", "Brady's 50 TDs", "Bonds' 73 HRs", "Gretzky's 215 Points"] },
    { prompt: "Who's the greatest women's basketball player?", tags: ["sports", "basketball"], options: ["Diana Taurasi", "Lisa Leslie", "Sheryl Swoopes", "Candace Parker"] },
    { prompt: "What's the best sports celebration of all time?", tags: ["sports", "general"], options: ["Terrell Owens' Sharpie", "Ickey Shuffle", "Lambeau Leap", "The Griddy"] },
    { prompt: "Who's the greatest draft pick ever?", subtitle: "Best value", tags: ["sports", "general"], options: ["Tom Brady (199th)", "Kobe Bryant (13th)", "Aaron Rodgers (24th)", "Draymond Green (35th)"] },
    { prompt: "What's the best rivalry in college sports?", tags: ["sports", "college"], options: ["Duke vs. UNC", "Ohio State vs. Michigan", "Army vs. Navy", "Auburn vs. Alabama"] },
    { prompt: "Who's the most dominant athlete in their sport?", tags: ["sports", "general"], options: ["Wayne Gretzky", "Don Bradman", "Serena Williams", "Michael Phelps"] },
    { prompt: "What's the best sports documentary?", subtitle: "Must-watch films", tags: ["sports", "movies"], options: ["The Last Dance", "O.J.: Made in America", "Hoop Dreams", "Senna"] },
    { prompt: "Who's the greatest Olympic track athlete?", tags: ["sports", "olympics", "track"], options: ["Usain Bolt", "Carl Lewis", "Jesse Owens", "Paavo Nurmi"] },
    { prompt: "What's the most iconic jersey number?", tags: ["sports", "general"], options: ["#23 (Jordan)", "#99 (Gretzky)", "#3 (Ruth)", "#10 (Messi/Pele)"] },
    { prompt: "Who's the best pass rusher in NFL history?", tags: ["sports", "football"], options: ["Reggie White", "Bruce Smith", "Lawrence Taylor", "J.J. Watt"] },
    { prompt: "What's the greatest underdog story in sports?", tags: ["sports", "general"], options: ["Miracle on Ice", "Leicester City 2016", "Buster Douglas vs. Tyson", "Greece Euro 2004"] },
    { prompt: "Who's the best sports commentator ever?", subtitle: "Voice of the game", tags: ["sports", "general"], options: ["Vin Scully", "Al Michaels", "John Madden", "Howard Cosell"] },
    { prompt: "What's the best extreme sport?", tags: ["sports", "extreme"], options: ["Skateboarding", "Snowboarding", "Surfing", "BMX"] },
    { prompt: "Who's the greatest Tour de France cyclist?", tags: ["sports", "cycling"], options: ["Eddy Merckx", "Bernard Hinault", "Miguel Indurain", "Chris Froome"] },
    { prompt: "What's the most iconic sports venue?", tags: ["sports", "general"], options: ["Madison Square Garden", "Wembley Stadium", "Yankee Stadium", "Camp Nou"] },
    { prompt: "Who's the best esports player of all time?", subtitle: "Digital dominance", tags: ["sports", "esports"], options: ["Faker (LoL)", "s1mple (CS:GO)", "Ninja (Fortnite)", "Flash (StarCraft)"] },
    { prompt: "What's the best sports mascot?", tags: ["sports", "general"], options: ["Phillie Phanatic", "Phoenix Suns Gorilla", "Benny the Bull", "Gritty"] },
    { prompt: "Who's the greatest soccer goalkeeper ever?", tags: ["sports", "soccer"], options: ["Lev Yashin", "Gianluigi Buffon", "Manuel Neuer", "Iker Casillas"] },
    { prompt: "What's the best women's sport to watch?", tags: ["sports", "general"], options: ["Women's Soccer", "Women's Tennis", "Women's Gymnastics", "Women's Basketball"] },
  ],
  culture: [
    { prompt: "Which social media platform is the best?", subtitle: "The eternal debate", tags: ["social media", "technology"], options: ["Instagram", "Twitter/X", "TikTok", "Threads"] },
    { prompt: "Which decade had the best pop culture?", subtitle: "Nostalgia wars", tags: ["decades", "nostalgia"], options: ["80s", "90s", "2000s", "2010s"] },
    { prompt: "What's the best way to listen to an album?", tags: ["music", "listening"], options: ["Vinyl", "Streaming", "CD", "Cassette"] },
    { prompt: "Which city has the best nightlife?", subtitle: "Where the party never stops", tags: ["nightlife", "cities"], options: ["New York", "Miami", "Las Vegas", "Los Angeles"] },
    { prompt: "What's the best meme format of all time?", tags: ["memes", "internet culture"], options: ["Distracted Boyfriend", "Drake Hotline Bling", "Woman Yelling at Cat", "Expanding Brain"] },
    { prompt: "Which streaming service is the best?", tags: ["streaming", "entertainment"], options: ["Netflix", "HBO Max", "Disney+", "Hulu"] },
    { prompt: "What's the best podcast genre?", subtitle: "What fills your commute?", tags: ["podcasts", "audio"], options: ["True Crime", "Comedy", "News/Politics", "Self-Help"] },
    { prompt: "Which era of stand-up comedy was the best?", tags: ["comedy", "decades"], options: ["80s (Carlin, Pryor)", "90s (Seinfeld, Rock)", "2000s (Chappelle, CK)", "2010s+ (Mulaney, Burr)"] },
    { prompt: "Which internet era was the peak?", subtitle: "When the web was wild", tags: ["internet", "nostalgia"], options: ["Early 2000s (Flash games, AIM)", "Late 2000s (YouTube rise)", "Early 2010s (Vine, peak Twitter)", "Now"] },
    { prompt: "What's the best design trend?", tags: ["design", "aesthetics"], options: ["Minimalism", "Y2K Revival", "Dark Mode Everything", "Brutalism"] },
    { prompt: "Which city has the best architecture?", subtitle: "Beauty in structure", tags: ["architecture", "cities"], options: ["Paris", "Barcelona", "Dubai", "Chicago"] },
    { prompt: "What's the best dating app?", tags: ["dating", "apps"], options: ["Hinge", "Bumble", "Tinder", "Raya"] },
    { prompt: "Work from home or office?", subtitle: "The post-pandemic debate", tags: ["work", "lifestyle"], options: ["Full remote", "Full office", "Hybrid"] },
    { prompt: "What's the best morning routine drink?", tags: ["morning", "drinks"], options: ["Coffee", "Tea", "Green juice", "Water only"] },
    { prompt: "Which book genre is superior?", tags: ["books", "reading"], options: ["Fiction", "Non-fiction", "Sci-Fi/Fantasy", "Mystery/Thriller"] },
    { prompt: "What's the best way to consume news?", subtitle: "Staying informed in 2026", tags: ["news", "media"], options: ["Newspapers", "News apps", "Podcasts", "Twitter/X"] },
    { prompt: "Which museum is the most impressive?", tags: ["museums", "culture"], options: ["The Louvre", "MoMA", "British Museum", "Smithsonian"] },
    { prompt: "What's the best theme park?", subtitle: "Ultimate entertainment destination", tags: ["theme parks", "entertainment"], options: ["Disney World", "Universal Studios", "Six Flags", "Cedar Point"] },
    { prompt: "Road trip or flying?", tags: ["travel", "transportation"], options: ["Road trip", "Flying"] },
    { prompt: "What's the best college experience?", subtitle: "Your formative years", tags: ["college", "education"], options: ["Big state school", "Small liberal arts", "Urban university", "Online/remote"] },
    { prompt: "Which wedding tradition is outdated?", tags: ["weddings", "traditions"], options: ["Bouquet toss", "Garter removal", "Father giving away bride", "None, keep them all"] },
    { prompt: "What's the best holiday to celebrate?", subtitle: "Peak festive energy", tags: ["holidays", "celebrations"], options: ["Christmas", "Halloween", "Thanksgiving", "New Year's Eve"] },
    { prompt: "Which language is most worth learning?", tags: ["languages", "education"], options: ["Spanish", "Mandarin", "French", "Japanese"] },
    { prompt: "What's the best pet?", tags: ["pets", "animals"], options: ["Dog", "Cat", "Bird", "No pets"] },
    { prompt: "Which life milestone matters most?", subtitle: "Adulting checkpoints", tags: ["life", "milestones"], options: ["First job", "Moving out", "Getting married", "Buying a home"] },
    { prompt: "Millennials or Gen Z?", subtitle: "Who's doing it better?", tags: ["generations", "culture"], options: ["Millennials", "Gen Z"] },
    { prompt: "What's the best celebrity feud?", tags: ["celebrities", "drama"], options: ["Taylor vs Kanye", "Drake vs Kendrick", "Nicki vs Cardi", "50 Cent vs Ja Rule"] },
    { prompt: "Which award show actually matters?", tags: ["awards", "entertainment"], options: ["Oscars", "Grammys", "Emmys", "None of them"] },
    { prompt: "What was the biggest viral moment?", subtitle: "Internet history", tags: ["viral", "internet"], options: ["Harlem Shake", "Ice Bucket Challenge", "Mannequin Challenge", "Yanny vs Laurel"] },
    { prompt: "Which type of influencer is most tolerable?", tags: ["influencers", "social media"], options: ["Fitness", "Beauty", "Tech", "Food"] },
    { prompt: "Is cancel culture good or bad?", subtitle: "The accountability debate", tags: ["cancel culture", "society"], options: ["Good (accountability)", "Bad (too harsh)", "It's complicated"] },
    { prompt: "What's the most nostalgic item from your childhood?", tags: ["nostalgia", "childhood"], options: ["Game Boy", "Tamagotchi", "Furbies", "Beanie Babies"] },
    { prompt: "What's the best classic board game?", tags: ["games", "board games"], options: ["Monopoly", "Scrabble", "Clue", "Risk"] },
    { prompt: "Which party game is the most fun?", subtitle: "Game night essential", tags: ["party games", "social"], options: ["Cards Against Humanity", "Werewolf/Mafia", "Codenames", "Charades"] },
    { prompt: "What's the best karaoke song?", tags: ["karaoke", "music"], options: ["Don't Stop Believin'", "Bohemian Rhapsody", "Livin' on a Prayer", "Sweet Caroline"] },
    { prompt: "Which fast food chain is superior?", subtitle: "Late night cravings", tags: ["food", "fast food"], options: ["McDonald's", "Chick-fil-A", "In-N-Out", "Shake Shack"] },
    { prompt: "What's the best pizza style?", tags: ["food", "pizza"], options: ["New York", "Chicago deep dish", "Neapolitan", "Detroit"] },
    { prompt: "Which coffee order says the most about you?", tags: ["coffee", "personality"], options: ["Black coffee", "Latte", "Cappuccino", "Frappuccino"] },
    { prompt: "What's the best midnight snack?", subtitle: "3am fuel", tags: ["food", "snacks"], options: ["Cereal", "Pizza rolls", "Ice cream", "Leftover takeout"] },
    { prompt: "Which workout trend is actually worth it?", tags: ["fitness", "trends"], options: ["CrossFit", "Peloton", "Hot yoga", "Just walking"] },
    { prompt: "What's the best way to watch sports?", tags: ["sports", "entertainment"], options: ["At the stadium", "Sports bar", "Home TV", "Streaming on phone"] },
    { prompt: "Which superhero universe is better?", subtitle: "The ultimate showdown", tags: ["movies", "superheroes"], options: ["Marvel (MCU)", "DC", "Neither"] },
    { prompt: "What's the best movie snack?", tags: ["movies", "food"], options: ["Popcorn", "Candy", "Nachos", "Nothing"] },
    { prompt: "Which TV show finale was the worst?", tags: ["tv", "endings"], options: ["Game of Thrones", "Dexter", "How I Met Your Mother", "Lost"] },
    { prompt: "What's the best binge-watching era?", subtitle: "Peak couch potato mode", tags: ["tv", "streaming"], options: ["Breaking Bad days", "Stranger Things hype", "The Office reruns", "Now (too many shows)"] },
    { prompt: "Which reality TV genre is most entertaining?", tags: ["reality tv", "entertainment"], options: ["Dating shows", "Competition shows", "Housewives franchises", "Survival shows"] },
    { prompt: "What's the best music video of all time?", tags: ["music", "music videos"], options: ["Thriller", "Single Ladies", "Virtual Insanity", "Take On Me"] },
    { prompt: "Which music festival is the ultimate experience?", subtitle: "Where legends are made", tags: ["music", "festivals"], options: ["Coachella", "Glastonbury", "Lollapalooza", "Burning Man"] },
    { prompt: "What's the best concert venue size?", tags: ["music", "concerts"], options: ["Intimate club", "Theater", "Arena", "Stadium"] },
    { prompt: "Which texting style is correct?", subtitle: "Grammar wars", tags: ["texting", "communication"], options: ["Proper punctuation", "No caps, no periods", "Voice messages", "Emojis only"] },
    { prompt: "What's the best way to make friends as an adult?", tags: ["friendship", "social"], options: ["Through work", "Hobby groups", "Apps (Bumble BFF)", "You don't"] },
    { prompt: "Which phone ecosystem is better?", subtitle: "The eternal war", tags: ["technology", "phones"], options: ["iPhone", "Android"] },
    { prompt: "What's the best smart home device?", tags: ["technology", "smart home"], options: ["Alexa", "Google Home", "Apple HomePod", "None (privacy concerns)"] },
    { prompt: "Which gaming console generation was the best?", tags: ["gaming", "consoles"], options: ["PS2/Xbox/GameCube", "PS3/Xbox 360/Wii", "PS4/Xbox One", "PS5/Xbox Series X"] },
    { prompt: "What's the best type of video game?", subtitle: "Your go-to genre", tags: ["gaming", "genres"], options: ["Open world RPG", "FPS", "Sports", "Indie puzzle"] },
    { prompt: "Which social media trend was the most cringe?", tags: ["social media", "cringe"], options: ["Planking", "Ice bucket fails", "TikTok dances", "Instagram vs reality"] },
    { prompt: "What's the best season?", tags: ["seasons", "weather"], options: ["Spring", "Summer", "Fall", "Winter"] },
    { prompt: "Which productivity method actually works?", subtitle: "Getting things done", tags: ["productivity", "work"], options: ["Pomodoro", "Time blocking", "GTD", "Just wing it"] },
    { prompt: "What's the best note-taking app?", tags: ["productivity", "apps"], options: ["Notion", "Apple Notes", "Evernote", "Good old pen and paper"] },
    { prompt: "Which type of humor is the best?", tags: ["humor", "comedy"], options: ["Sarcasm", "Puns", "Dark humor", "Physical comedy"] },
    { prompt: "What's the best way to spend a Sunday?", subtitle: "The perfect day off", tags: ["lifestyle", "relaxation"], options: ["Brunch and chill", "Meal prep and errands", "Adventure/exploring", "Pure rest"] },
    { prompt: "Which fictional universe would you want to live in?", tags: ["fiction", "fantasy"], options: ["Star Wars", "Harry Potter", "Lord of the Rings", "Marvel"] },
  ],
  gaming: [
    { prompt: "What's the best open world game?", subtitle: "Exploration at its finest", tags: ["openworld", "adventure"], options: ["Red Dead Redemption 2", "The Witcher 3", "Breath of the Wild", "Elden Ring"] },
    { prompt: "What's the best gaming console?", subtitle: "The eternal debate", tags: ["console", "hardware"], options: ["PlayStation", "Xbox", "Nintendo Switch", "PC"] },
    { prompt: "What's the best multiplayer game?", tags: ["multiplayer", "competitive"], options: ["Overwatch", "Apex Legends", "Valorant", "Call of Duty"] },
    { prompt: "What's the best video game soundtrack?", subtitle: "Music that moves us", tags: ["soundtrack", "music"], options: ["The Last of Us", "Halo", "Final Fantasy VII", "Undertale"] },
    { prompt: "What's the best FromSoftware game?", tags: ["fromsoftware", "souls"], options: ["Dark Souls", "Bloodborne", "Sekiro", "Elden Ring"] },
    { prompt: "What's the best Zelda game?", subtitle: "The hero's journey continues", tags: ["zelda", "nintendo"], options: ["Ocarina of Time", "Breath of the Wild", "A Link to the Past", "Majora's Mask"] },
    { prompt: "What's the best indie game?", tags: ["indie", "creative"], options: ["Hollow Knight", "Celeste", "Hades", "Stardew Valley"] },
    { prompt: "What's the best battle royale?", tags: ["battleroyale", "multiplayer"], options: ["Fortnite", "APEX Legends", "PUBG", "Warzone"] },
    { prompt: "What's the best RPG of all time?", subtitle: "Epic adventures and character builds", tags: ["rpg", "story"], options: ["Final Fantasy VII", "The Witcher 3", "Skyrim", "Chrono Trigger"] },
    { prompt: "What's the best FPS game?", tags: ["fps", "shooter"], options: ["Half-Life 2", "Doom Eternal", "Halo 3", "Titanfall 2"] },
    { prompt: "What's the best platformer?", subtitle: "Jump, run, and collect", tags: ["platformer", "classic"], options: ["Super Mario Odyssey", "Celeste", "Super Meat Boy", "Hollow Knight"] },
    { prompt: "What's the best racing game?", tags: ["racing", "sports"], options: ["Mario Kart 8", "Forza Horizon 5", "Gran Turismo 7", "Need for Speed: Most Wanted"] },
    { prompt: "What's the best fighting game?", tags: ["fighting", "competitive"], options: ["Street Fighter 6", "Tekken 8", "Super Smash Bros. Ultimate", "Mortal Kombat 11"] },
    { prompt: "What's the best horror game?", subtitle: "Sleep is for the weak", tags: ["horror", "scary"], options: ["Resident Evil 4", "Silent Hill 2", "Dead Space", "Amnesia: The Dark Descent"] },
    { prompt: "What's the best strategy game?", tags: ["strategy", "tactical"], options: ["Civilization VI", "StarCraft II", "XCOM 2", "Age of Empires II"] },
    { prompt: "What's the best MMO?", subtitle: "Living worlds and endless grind", tags: ["mmo", "multiplayer"], options: ["World of Warcraft", "Final Fantasy XIV", "Guild Wars 2", "EVE Online"] },
    { prompt: "What's the best mobile game?", tags: ["mobile", "casual"], options: ["Clash of Clans", "Genshin Impact", "Among Us", "Pokemon GO"] },
    { prompt: "What's the best VR game?", tags: ["vr", "immersive"], options: ["Half-Life: Alyx", "Beat Saber", "Resident Evil 4 VR", "Superhot VR"] },
    { prompt: "Who's the best video game villain?", subtitle: "Evil never looked so good", tags: ["villain", "character"], options: ["Sephiroth", "GLaDOS", "Vaas Montenegro", "Handsome Jack"] },
    { prompt: "Who's the best video game protagonist?", tags: ["protagonist", "character"], options: ["Link", "Master Chief", "Geralt of Rivia", "Arthur Morgan"] },
    { prompt: "What's the best boss fight?", subtitle: "Legendary showdowns", tags: ["boss", "combat"], options: ["Ornstein & Smough", "Ludwig", "Isshin Ashina", "Malenia"] },
    { prompt: "What's the best plot twist?", tags: ["story", "twist"], options: ["BioShock", "The Last of Us", "Knights of the Old Republic", "Undertale"] },
    { prompt: "What's the best co-op game?", subtitle: "Better together", tags: ["coop", "multiplayer"], options: ["It Takes Two", "Portal 2", "Borderlands 2", "Left 4 Dead 2"] },
    { prompt: "What's the best couch multiplayer game?", tags: ["local", "party"], options: ["Mario Kart", "Super Smash Bros.", "Overcooked 2", "Gang Beasts"] },
    { prompt: "What's the best game studio?", subtitle: "The masterminds behind the magic", tags: ["studio", "developer"], options: ["Nintendo", "Rockstar Games", "Naughty Dog", "FromSoftware"] },
    { prompt: "What's the best game engine?", tags: ["engine", "development"], options: ["Unreal Engine", "Unity", "CryEngine", "Godot"] },
    { prompt: "What's the best speedrun game?", tags: ["speedrun", "challenge"], options: ["Super Mario 64", "Celeste", "Portal", "Dark Souls"] },
    { prompt: "What's the best esports title?", subtitle: "Competitive gaming at its peak", tags: ["esports", "competitive"], options: ["League of Legends", "Counter-Strike 2", "Dota 2", "Valorant"] },
    { prompt: "What's the best gaming peripheral brand?", tags: ["hardware", "gear"], options: ["Razer", "Logitech", "SteelSeries", "Corsair"] },
    { prompt: "What's the best gaming decade?", tags: ["retro", "era"], options: ["1990s", "2000s", "2010s", "2020s"] },
    { prompt: "What's the best retro console?", subtitle: "Nostalgia hits hard", tags: ["retro", "console"], options: ["SNES", "Sega Genesis", "PlayStation 1", "Nintendo 64"] },
    { prompt: "What's the best remake?", tags: ["remake", "remaster"], options: ["Resident Evil 2", "Final Fantasy VII Remake", "Demon's Souls", "Shadow of the Colossus"] },
    { prompt: "What's the best DLC expansion?", subtitle: "When more is actually more", tags: ["dlc", "expansion"], options: ["The Witcher 3: Blood and Wine", "Bloodborne: The Old Hunters", "Skyrim: Dragonborn", "Mass Effect 2: Lair of the Shadow Broker"] },
    { prompt: "What's the best game trailer?", tags: ["trailer", "hype"], options: ["Dead Island", "Gears of War", "The Last of Us Part II", "Cyberpunk 2077"] },
    { prompt: "What's the most iconic loading screen?", tags: ["loadscreen", "nostalgia"], options: ["Skyrim", "The Elder Scrolls IV: Oblivion", "Grand Theft Auto V", "Assassin's Creed"] },
    { prompt: "What's the best game over screen?", subtitle: "Death has never been so memorable", tags: ["gameover", "death"], options: ["Dark Souls", "Metal Gear Solid", "Resident Evil", "Minecraft"] },
    { prompt: "What's the best character creation system?", tags: ["customization", "rpg"], options: ["Skyrim", "Baldur's Gate 3", "Dragon Age: Inquisition", "Fallout 4"] },
    { prompt: "What's the best skill tree system?", tags: ["progression", "rpg"], options: ["Path of Exile", "Borderlands 2", "The Witcher 3", "Skyrim"] },
    { prompt: "What's the best stealth game?", subtitle: "Silent but deadly", tags: ["stealth", "action"], options: ["Metal Gear Solid 3", "Dishonored", "Hitman 3", "Splinter Cell: Chaos Theory"] },
    { prompt: "What's the best survival game?", tags: ["survival", "crafting"], options: ["Minecraft", "Subnautica", "The Forest", "Ark: Survival Evolved"] },
    { prompt: "What's the best sandbox game?", subtitle: "Your world, your rules", tags: ["sandbox", "creative"], options: ["Minecraft", "Terraria", "Garry's Mod", "Roblox"] },
    { prompt: "What's the best story-driven game?", tags: ["story", "narrative"], options: ["The Last of Us", "Red Dead Redemption 2", "God of War", "Life is Strange"] },
    { prompt: "What's the best roguelike?", tags: ["roguelike", "challenge"], options: ["Hades", "Dead Cells", "The Binding of Isaac", "Slay the Spire"] },
    { prompt: "What's the best puzzle game?", subtitle: "Brain bending at its finest", tags: ["puzzle", "logic"], options: ["Portal 2", "The Witness", "Tetris Effect", "Baba Is You"] },
    { prompt: "What's the best metroidvania?", tags: ["metroidvania", "exploration"], options: ["Hollow Knight", "Metroid Dread", "Ori and the Blind Forest", "Castlevania: Symphony of the Night"] },
    { prompt: "What's the best sports game franchise?", tags: ["sports", "simulation"], options: ["FIFA/EA Sports FC", "NBA 2K", "Madden NFL", "MLB The Show"] },
    { prompt: "What's the best fishing minigame?", subtitle: "Surprisingly addictive", tags: ["minigame", "fishing"], options: ["Stardew Valley", "The Legend of Zelda: Twilight Princess", "Final Fantasy XV", "Ocarina of Time"] },
    { prompt: "What's the best card game spinoff?", tags: ["cardgame", "spinoff"], options: ["Gwent", "Hearthstone", "The Witcher 3: Gwent", "Final Fantasy VIII: Triple Triad"] },
    { prompt: "What's the best open world city?", subtitle: "Urban exploration done right", tags: ["openworld", "city"], options: ["Los Santos (GTA V)", "Night City (Cyberpunk 2077)", "Kamurocho (Yakuza)", "Liberty City (GTA IV)"] },
    { prompt: "What's the best weapon in gaming?", tags: ["weapon", "combat"], options: ["Master Sword", "BFG 9000", "Portal Gun", "Energy Sword"] },
    { prompt: "What's the best video game dog?", subtitle: "Good boys and girls only", tags: ["character", "companion"], options: ["Dogmeat (Fallout)", "D.D. (Metal Gear Solid V)", "Chop (GTA V)", "Rush (Mega Man)"] },
    { prompt: "What's the best gaming moment of the 2010s?", tags: ["moment", "memorable"], options: ["Breath of the Wild release", "The Last of Us giraffe scene", "Undertale's true ending", "God of War's one-shot camera"] },
    { prompt: "What's the best tower defense game?", tags: ["towerdefense", "strategy"], options: ["Bloons TD 6", "Plants vs. Zombies", "Kingdom Rush", "Defense Grid"] },
    { prompt: "What's the best simulation game?", subtitle: "Living out virtual dreams", tags: ["simulation", "management"], options: ["The Sims 4", "Cities: Skylines", "Stardew Valley", "Euro Truck Simulator 2"] },
    { prompt: "What's the best handheld console?", tags: ["handheld", "portable"], options: ["Game Boy Advance", "Nintendo DS", "PlayStation Portable", "Nintendo Switch"] },
    { prompt: "What's the best video game quote?", subtitle: "Words that echo forever", tags: ["quote", "memorable"], options: ["Would you kindly?", "War never changes", "It's dangerous to go alone", "The cake is a lie"] },
    { prompt: "What's the best gaming companion?", tags: ["companion", "sidekick"], options: ["Ellie (The Last of Us)", "Atreus (God of War)", "Elizabeth (BioShock Infinite)", "Tails (Sonic)"] },
    { prompt: "What's the best JRPG?", subtitle: "Turn-based excellence", tags: ["jrpg", "rpg"], options: ["Final Fantasy VII", "Persona 5", "Chrono Trigger", "Dragon Quest XI"] },
    { prompt: "What's the best MOBA?", tags: ["moba", "competitive"], options: ["League of Legends", "Dota 2", "Smite", "Heroes of the Storm"] },
    { prompt: "What's the best gaming trilogy?", tags: ["trilogy", "series"], options: ["Mass Effect", "Dark Souls", "The Witcher", "Uncharted"] },
    { prompt: "What's the best gaming Easter egg?", subtitle: "Hidden gems and secrets", tags: ["easteregg", "secret"], options: ["Konami Code", "Minecraft's upside-down mob", "GTA San Andreas' Bigfoot mystery", "Halo 3's hidden skulls"] },
    { prompt: "What's the best gaming controller?", tags: ["controller", "hardware"], options: ["DualSense", "Xbox Elite Controller", "Nintendo Switch Pro Controller", "DualShock 4"] },
  ],
  style: [
    { prompt: "Which sneaker brand reigns supreme?", subtitle: "The eternal debate", tags: ["fashion", "sneakers"], options: ["Nike", "Adidas", "New Balance", "Jordan"] },
    { prompt: "What's the best sneaker silhouette of all time?", tags: ["fashion", "sneakers"], options: ["Air Jordan 1", "Air Force 1", "Adidas Samba", "Nike Dunk"] },
    { prompt: "Which fashion decade had the best style?", subtitle: "Time to pick a side", tags: ["fashion", "style"], options: ["1960s", "1980s", "1990s", "2000s"] },
    { prompt: "What's the greatest fashion collaboration ever?", tags: ["fashion", "streetwear"], options: ["Nike x Off-White", "Adidas x Yeezy", "Supreme x Louis Vuitton", "H&M x Balmain"] },
    { prompt: "Which luxury watch brand is the most prestigious?", subtitle: "Wrist game debate", tags: ["fashion", "accessories"], options: ["Rolex", "Patek Philippe", "Audemars Piguet", "Omega"] },
    { prompt: "What's the best sunglasses style?", tags: ["fashion", "accessories"], options: ["Aviators", "Wayfarers", "Round frames", "Cat-eye"] },
    { prompt: "Which streetwear brand defined a generation?", tags: ["fashion", "streetwear"], options: ["Supreme", "Stussy", "BAPE", "Palace"] },
    { prompt: "Who had the best red carpet look of 2024?", subtitle: "The most iconic moment", tags: ["fashion", "celebrity"], options: ["Zendaya at Dune premiere", "Timothee at Venice FF", "Anya Taylor-Joy at Emmys", "Bad Bunny at Met Gala"] },
    { prompt: "Which denim brand makes the perfect jean?", tags: ["fashion", "denim"], options: ["Levi's", "Wrangler", "AG", "Citizens of Humanity"] },
    { prompt: "What's the best t-shirt fit?", subtitle: "The foundation of every outfit", tags: ["fashion", "basics"], options: ["Oversized", "Fitted", "Boxy crop", "Classic regular"] },
    { prompt: "Which suit style is most timeless?", tags: ["fashion", "formalwear"], options: ["Italian slim fit", "British tailored", "American sack suit", "Double-breasted"] },
    { prompt: "What's the superior hat style?", tags: ["fashion", "accessories"], options: ["Dad cap", "Snapback", "Beanie", "Bucket hat"] },
    { prompt: "Which luxury bag brand is worth the investment?", subtitle: "The bag debate", tags: ["fashion", "accessories"], options: ["Hermes", "Chanel", "Louis Vuitton", "Bottega Veneta"] },
    { prompt: "What's the best jewelry metal?", tags: ["fashion", "accessories"], options: ["Gold", "Silver", "Platinum", "Rose gold"] },
    { prompt: "Which tattoo style ages best?", subtitle: "Permanent decisions", tags: ["fashion", "body art"], options: ["Traditional", "Fine line", "Japanese", "Black & grey realism"] },
    { prompt: "What's the most iconic hair trend?", tags: ["fashion", "beauty"], options: ["Curtain bangs", "Mullet revival", "Buzz cut", "Shag"] },
    { prompt: "Which beard style is the most attractive?", tags: ["fashion", "grooming"], options: ["Full beard", "Stubble", "Goatee", "Clean shaven"] },
    { prompt: "What's the best nail art style?", subtitle: "Fingers on point", tags: ["fashion", "beauty"], options: ["French tips", "Chrome finish", "Minimalist nude", "Maximalist designs"] },
    { prompt: "Which designer perfume is most iconic?", tags: ["fashion", "fragrance"], options: ["Chanel No. 5", "Dior Sauvage", "Tom Ford Black Orchid", "Le Labo Santal 33"] },
    { prompt: "What's the best fashion capital?", subtitle: "Style central", tags: ["fashion", "culture"], options: ["Paris", "Milan", "New York", "Tokyo"] },
    { prompt: "Which fashion magazine still matters?", tags: ["fashion", "media"], options: ["Vogue", "GQ", "Esquire", "i-D"] },
    { prompt: "Fast fashion or luxury investment pieces?", subtitle: "The eternal clothing dilemma", tags: ["fashion", "style"], options: ["Fast fashion", "Luxury only", "Mix of both"] },
    { prompt: "Thrifting or buying new?", tags: ["fashion", "shopping"], options: ["Thrift stores", "Brand new", "Vintage shops", "Online resale"] },
    { prompt: "What's the superior aesthetic?", tags: ["fashion", "style"], options: ["Minimalism", "Maximalism", "Eclectic mix"] },
    { prompt: "Which athleisure brand does it best?", subtitle: "Gym to street", tags: ["fashion", "athleisure"], options: ["Lululemon", "Alo Yoga", "Gymshark", "Nike"] },
    { prompt: "What's the best workwear brand?", tags: ["fashion", "workwear"], options: ["Carhartt", "Dickies", "Patagonia", "Filson"] },
    { prompt: "Which festival fashion era was peak?", subtitle: "Coachella chronicles", tags: ["fashion", "festival"], options: ["2010s flower crowns", "2020s Y2K revival", "1990s grunge", "1960s boho"] },
    { prompt: "What's the best wedding attire vibe?", tags: ["fashion", "formalwear"], options: ["Classic black tie", "Beach casual", "Boho chic", "Modern minimalist"] },
    { prompt: "Which profession has the best uniform style?", tags: ["fashion", "uniforms"], options: ["Pilot", "Chef", "Military", "Medical scrubs"] },
    { prompt: "Who is the ultimate fashion icon?", subtitle: "Style royalty", tags: ["fashion", "icons"], options: ["Audrey Hepburn", "David Bowie", "Rihanna", "Pharrell"] },
    { prompt: "What's the most versatile color palette?", tags: ["fashion", "style"], options: ["All black", "Earth tones", "Monochrome", "Pastels"] },
    { prompt: "Which pattern is most timeless?", tags: ["fashion", "patterns"], options: ["Stripes", "Plaid", "Animal print", "Floral"] },
    { prompt: "What's the best fabric for everyday wear?", subtitle: "Comfort meets style", tags: ["fashion", "materials"], options: ["Cotton", "Linen", "Wool", "Cashmere"] },
    { prompt: "Which boot style is most iconic?", tags: ["fashion", "footwear"], options: ["Chelsea boots", "Doc Martens", "Timberlands", "Cowboy boots"] },
    { prompt: "What's the best dress shoe?", tags: ["fashion", "footwear"], options: ["Oxford", "Loafer", "Derby", "Monk strap"] },
    { prompt: "Which sandal reigns supreme?", subtitle: "Summer feet", tags: ["fashion", "footwear"], options: ["Birkenstock", "Teva", "Flip flops", "Slides"] },
    { prompt: "What's the most essential outerwear piece?", tags: ["fashion", "outerwear"], options: ["Leather jacket", "Denim jacket", "Trench coat", "Bomber jacket"] },
    { prompt: "Which winter coat is best?", subtitle: "Cold weather champion", tags: ["fashion", "outerwear"], options: ["Puffer", "Wool overcoat", "Parka", "Peacoat"] },
    { prompt: "What's the superior sock choice?", tags: ["fashion", "accessories"], options: ["Ankle socks", "Crew socks", "No-show", "Knee-high"] },
    { prompt: "Which tie style is most professional?", tags: ["fashion", "formalwear"], options: ["Silk necktie", "Bow tie", "Skinny tie", "No tie"] },
    { prompt: "What's the best belt material?", tags: ["fashion", "accessories"], options: ["Leather", "Canvas", "Woven fabric", "Chain"] },
    { prompt: "Which scarf style is most versatile?", subtitle: "Neck game strong", tags: ["fashion", "accessories"], options: ["Cashmere wrap", "Silk square", "Chunky knit", "Bandana"] },
    { prompt: "What's the best glove style?", tags: ["fashion", "accessories"], options: ["Leather driving gloves", "Knit mittens", "Tech-friendly gloves", "Fingerless"] },
    { prompt: "Which shorts length is ideal?", tags: ["fashion", "bottoms"], options: ["Above knee", "At knee", "Mid-thigh", "Short shorts"] },
    { prompt: "What's the superior skirt silhouette?", tags: ["fashion", "bottoms"], options: ["Mini", "Midi", "Maxi", "Pencil"] },
    { prompt: "Which dress style is most flattering?", subtitle: "The perfect dress", tags: ["fashion", "dresses"], options: ["Wrap dress", "Shirt dress", "Slip dress", "A-line"] },
    { prompt: "What's the best blazer fit?", tags: ["fashion", "tailoring"], options: ["Oversized", "Fitted", "Boyfriend", "Cropped"] },
    { prompt: "Which sweater style is coziest?", tags: ["fashion", "knitwear"], options: ["Turtleneck", "Crewneck", "Cardigan", "Hoodie"] },
    { prompt: "What's the most iconic logo?", subtitle: "Brand recognition", tags: ["fashion", "branding"], options: ["Nike Swoosh", "Adidas Trefoil", "Polo Ralph Lauren", "Lacoste Crocodile"] },
    { prompt: "Which pocket style is most functional?", tags: ["fashion", "design"], options: ["Cargo pockets", "Patch pockets", "Welt pockets", "Kangaroo pocket"] },
    { prompt: "What's the best collar type?", tags: ["fashion", "shirts"], options: ["Spread collar", "Button-down", "Mandarin collar", "Cuban collar"] },
    { prompt: "Which closure is superior?", tags: ["fashion", "design"], options: ["Buttons", "Zipper", "Snaps", "Velcro"] },
    { prompt: "What's the most comfortable underwear style?", subtitle: "Foundation matters", tags: ["fashion", "basics"], options: ["Boxer briefs", "Briefs", "Boxers", "Trunks"] },
    { prompt: "Which bra style is most versatile?", tags: ["fashion", "basics"], options: ["T-shirt bra", "Bralette", "Sports bra", "Push-up"] },
    { prompt: "What's the best pajama style?", tags: ["fashion", "loungewear"], options: ["Matching set", "Oversized tee", "Silk slip", "Onesie"] },
    { prompt: "Which swimwear style is most flattering?", subtitle: "Beach season", tags: ["fashion", "swimwear"], options: ["One-piece", "Bikini", "Tankini", "Board shorts"] },
    { prompt: "What's the superior activewear bottom?", tags: ["fashion", "athleisure"], options: ["Leggings", "Joggers", "Bike shorts", "Track pants"] },
    { prompt: "Which earring style is most timeless?", tags: ["fashion", "jewelry"], options: ["Studs", "Hoops", "Dangles", "Huggies"] },
    { prompt: "What's the best necklace length?", tags: ["fashion", "jewelry"], options: ["Choker", "Princess", "Matinee", "Chain layering"] },
    { prompt: "Which ring style is most elegant?", subtitle: "Finger bling", tags: ["fashion", "jewelry"], options: ["Solitaire", "Signet ring", "Stacking rings", "Statement ring"] },
    { prompt: "What's the best watch strap material?", tags: ["fashion", "accessories"], options: ["Metal bracelet", "Leather", "NATO strap", "Rubber"] },
    { prompt: "Which eyewear trend is here to stay?", tags: ["fashion", "accessories"], options: ["Blue light glasses", "Transition lenses", "Oversized frames", "Colored lenses"] },
  ],
};

// ---------------------------------------------------------------------------
// Seed function
// ---------------------------------------------------------------------------

async function seed() {
  console.log("🌱 Starting seed...\n");

  // ------ Clear existing data (respect FK order) ------
  console.log("Clearing existing data...");
  await db.delete(impressions);
  console.log("  ✓ Cleared impressions");
  await db.delete(votes);
  console.log("  ✓ Cleared votes");
  await db.delete(options);
  console.log("  ✓ Cleared options");
  await db.delete(questions);
  console.log("  ✓ Cleared questions");
  await db.delete(categories);
  console.log("  ✓ Cleared categories");
  console.log("");

  // ------ Insert categories ------
  console.log("Inserting categories...");
  const insertedCategories = await db
    .insert(categories)
    .values(categoryData)
    .returning({ id: categories.id, slug: categories.slug });

  const categoryMap = new Map<string, string>();
  for (const cat of insertedCategories) {
    categoryMap.set(cat.slug, cat.id);
  }
  console.log(`  ✓ Inserted ${insertedCategories.length} categories\n`);

  // ------ Insert questions & options ------
  let totalQuestions = 0;
  let totalOptions = 0;

  for (const [slug, qs] of Object.entries(questionData)) {
    const categoryId = categoryMap.get(slug);
    if (!categoryId) {
      console.error(`  ✗ Category "${slug}" not found — skipping`);
      continue;
    }

    console.log(`Inserting questions for "${slug}"...`);

    for (const q of qs) {
      const [insertedQuestion] = await db
        .insert(questions)
        .values({
          categoryId,
          prompt: q.prompt,
          subtitle: q.subtitle ?? null,
          tags: q.tags ?? null,
          status: "active",
        })
        .returning({ id: questions.id });

      totalQuestions++;

      const optionValues = q.options.map((name, idx) => ({
        questionId: insertedQuestion.id,
        name,
        sortOrder: idx,
      }));

      await db.insert(options).values(optionValues);
      totalOptions += optionValues.length;
    }

    console.log(`  ✓ ${qs.length} questions inserted`);
  }

  console.log(`\n🎉 Seed complete!`);
  console.log(`   ${insertedCategories.length} categories`);
  console.log(`   ${totalQuestions} questions`);
  console.log(`   ${totalOptions} options`);
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

seed()
  .then(() => {
    process.exit(0);
  })
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
